# Site settings
title: METRO.org
email: info@metro.org
description: METRO is a lab where New York's libraries and archives come together to learn, innovate, and collaborate on digital initiatives.
baseurl: "/metro.org"
url: "http://metro.org"

footer:
  address:
    - line: Metropolitan New York Library Council
    - line: 57 East 11th Street, Fourth Floor
    - line: New York, NY 10003
  phone: 212.228.2320
  fax: 212.228.2598

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
- title: twitter
  url: http://twitter.com/mnylc
- title: facebook
  url:
- title: github
  url: http://github.com/mnylc

# Content settings
defaults:
  -
    scope:
      type: "posts"
      path: "_posts/jobs"
    values:
      permalink: "/jobs/:title"
      tags:
        - job
  -
    scope:
      type: "posts"
      path: "_posts/news"
    values:
      permalink: "/news/:title"
      tags:
        - news
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# Build settings
markdown: kramdown

# Attribution
attribution:
  image:
    source: Seymour B. Durst Old York Library Collection
    url: http://www.dcmny.org/islandora/object/cuny34thstreet%3A851
  theme:
    source: Rick Kim
    name: agency
    url: https://github.com/y7kim/agency-jekyll-theme
